name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@octocat'

      - name: Enable corepack 📦
        run: corepack enable

      - name: Install dependencies 🧹
        run: yarn

      - name: Run tests 🧪
        run: yarn run test

      - name: Build 🔨
        run: yarn run build

      - name: Publish 🚀
        run: yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
